using System;
using System.Collections.Generic;
using System.Text;

namespace Comp7211GroupProject.Classes.API.Models
{
    public class Comments : IComments
    {
        public int Id { get; set; }
        public int Uid { get; set; }
        public int PostId { get; set; }
        public string Comment { get; set; }

        // Below was generated by scaffolding to represent our Foreign Keys
        // DO NOT REMOVE. THE DB CONTEXT USES THEM

        public virtual Posts Post { get; set; }
        public virtual Users U { get; set; }
    }
}
