using System;
using System.Collections.Generic;
using System.Text;

namespace Comp7211GroupProject.Classes.API.Models
{
    public class Posts : IPosts
    {
        public Posts()
        {
            Comments = new HashSet<Comments>();
        }

        public int Id { get; set; }
        public int Uid { get; set; }
        public string Post { get; set; }
        public int UpVote { get; set; }
        public int DownVote { get; set; }

        // Below was generated by scaffolding to represent our Foreign Keys
        // DO NOT REMOVE. THE DB CONTEXT USES THEM

        public virtual Users U { get; set; }
        public virtual ICollection<Comments> Comments { get; set; }
    }
}
